#!/bin/bash
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /home/$1/selfsigned.key -out /home/$1/selfsigned.crt -subj "/C=RU/ST=Tatarstan/L=Kazan/O=Andersen_devops_course_may/OU=Zigangirov Gizar/CN=192.168.33.10"
