---
  - name       : Deploy flask app to vm
    hosts      : vmflask
    become     : yes

    vars:
      username: vagrant
      rule_file: rule_flaskapp
      #path to app
      app_path   : /home/vagrant/
      #path to service
      service_path  : /etc/systemd/system/
      #necessary packages to install
      nes_env:
        - python3
        - python3-pip
        - python3-dev
        - python-setuptools
        - libssl-dev
        - libffi-dev
        - ufw

      #app file
      app_file: flask_app.py
      #myscript: create_ssl
      #service file
      service_file: flask_app.service

    tasks:
      #get the target machine ip
      #- set_fact: target_ip={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      #- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

      - name: Update the system and install necessary packages via loop
        apt:
          name          : "{{ nes_env }}"
          force         : yes
          update_cache  : yes
          autoremove    : yes
          autoclean     : yes

      - name: Creating app dir
        file:
          path : "{{ app_path }}"
          state: directory
          mode : '0775'

      - name: installing flask
        pip:
          executable: pip3
          name: flask
          state: latest
      - name: pip3 command
        command: pip3 install --upgrade pip

      - name: installing rust
        pip:
          executable: pip3
          name: rust
          state: latest

      - name: installing rust
        pip:
          executable: pip3
          name: pyopenssl
          state: latest

      - name: installing emoji
        pip:
          executable: pip3
          name: emoji
          state: latest

      - name: copy necessary files
        copy:
          src : "{{ app_file }}"
          dest: "{{ app_path }}"
          mode: '0775'

      #- name: copy necessary files
      #  copy:
      #    src : "{{ myscript }}"
      #    dest: "{{ app_path }}"
      #    mode: '0775'

      - name: create ssl
        script: create_ssl "{{ username }}"

      - name: copy systemd files
        copy:
          src : "{{ service_file }}"
          dest: "{{ service_path }}"

      #- name  : create ssl-keys
      #  script: create_ssl

      - name: enable ufw
        ufw:
          state: enabled


      - name: 15a-Copy file rule for flask
        copy:
          src: "{{ rule_file }}"
          dest: /etc/ufw/applications.d
          owner: root
          group: root
          mode: '0644'
        notify:
          - restart ufw

      - name: rules for ufw
        ufw:
          rule: allow
          name: '{{ item }}'
        loop:
          - "WWW Full"
          - "OpenSSH"
          - "flask_app"
        notify:
          - restart ufw



      - name: copy sshd file
        copy:
         src  : sshd_config
         dest : /etc/ssh/
         force: yes

      - name: ssh restart
        command: systemctl restart sshd

      - name: enable service
        service:
          name   : flask_app.service
          enabled: yes

      - name: start service
        service:
          name : flask_app.service
          state: started


    handlers:
      - name: restart ufw
        service: name=ufw state=restarted
