---
- hosts: flask_servers
  gather_facts: no
  become: yes
  tasks:
  - name: creating /var/www/ansible_task dir
    file:
      path: /var/www/ansible_task
      state: directory

  - name: copy flask app to flask_servers
    copy:
      src: /$PWD/flask_app/main.py
      dest: /var/www/ansible_task/main.py

  - name: update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  #- name: installing py3
  #  apt:
  #    name: python3
  #    update_cache: yes

  - name: installing py3 pip3 setuptools
    apt:
      name:
        - python3
        - python3-pip
        - python-setuptools
      state: latest
      update_cache: yes

  - name: installing flask
    pip:
      executable: pip3
      name: flask
      state: latest


  - name: Disable root login over ssh
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify:
        - Restart sshd

  - name: copy flask service
    copy:
      src: /$PWD/flaskapp.service
      dest: /etc/systemd/system/flaskapp.service

  - name: enable flask service
    service: name=flaskapp.service enabled=yes

  - name: start flaskapp service
    service: name=flaskapp.service state=started
