---
- hosts: flask_servers
  gather_facts: no
  become: yes
  tasks:
  - name: creating /var/www/ansible_task dir
    file:
      path: /var/www/ansible_task
      state: directory

  - name: copy flask app to flask_servers
    copy:
      src: /$PWD/flask_app/main.py
      dest: /var/www/ansible_task/main.py

  - name: update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: installing py3
    apt:
      name: python3
      update_cache: yes

  - name: installing pip3
    apt:
      name: python3-pip
      update_cache: yes

  - name: installing flask
    pip:
      executable: pip3
      name: flask
      state: latest

  - name: run flask app
    shell: |
      nohup python3 /var/www/ansible_task/main.py > log.txt 2>&1 &
