---
- hosts: flask_servers
  gather_facts: no
  become: yes
  tasks:
  - name: copy flask app to flask_servers
    copy:
      src: /$PWD/flask_app/main.py
      dest: /home/vagrant/main.py

  - name: update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  #- name: installing py3
  #  apt:
  #    name: python3
  #    update_cache: yes

  - name: installing py3 pip3 setuptools
    apt:
      name:
        - python3
        - python3-pip
        - python-setuptools
      state: latest
      update_cache: yes

  - name: installing flask
    pip:
      executable: pip3
      name: flask
      state: latest


  - name: copy flask service
    copy:
      src: /$PWD/flaskapp.service
      dest: /etc/systemd/system/flaskapp.service

  - name: enable flask service
    service: name=flaskapp.service enabled=yes

  - name: start flaskapp service
    service: name=flaskapp.service state=started


  - name: Disable root login over ssh
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin yes" line="PermitRootLogin no" state=present
    notify:
      - Restart sshd

  - name: Allow pubkey auth
    lineinfile: dest=/etc/ssh/sshd_config regexp="^(.\w*)PubkeyAuthentication " line="PubkeyAuthentication yes" state=present
    notify:
      - Restart sshd


  - name: Disable password auth
    lineinfile: dest=/etc/ssh/sshd_config regexp="^(\w*[^Pubkey])Authentication yes" line="^(\w*[^Pubkey])Authentication no" state=present
    notify:
      - Restart sshd

#  - name: Disable kerberos auth
#    lineinfile: dest=/etc/ssh/sshd_config regexp="^#KerberosAuthentication" line="KerberosAuthentication no" state=present


#  - name: Allow pubkey auth
#    lineinfile: dest=/etc/ssh/sshd_config regexp="^(.\w*)PubkeyAuthentication" line="PubkeyAuthentication yes" state=present
#    notify:
#        - Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
